// Constantes compartidas del módulo Objeciones.
// Movido desde ObjecionesSection.tsx (Fase 0 · Paso 0.1).

import type { ObjecionTipo, TabConfig } from "./types";

export const TIPO_RUTA: Record<ObjecionTipo, string> = {
  AOBAGRECL: "agrecl", OBJEINCL: "incl", AOBCUPS: "cups", AOBCIL: "cil",
};

export const TIPO_GENERA_ZIP: Record<ObjecionTipo, boolean> = {
  AOBAGRECL: true, OBJEINCL: false, AOBCUPS: false, AOBCIL: false,
};

export const TIPO_GENERA_ONE: Record<ObjecionTipo, boolean> = {
  AOBAGRECL: true, OBJEINCL: false, AOBCUPS: false, AOBCIL: false,
};

export const TABS: TabConfig[] = [
  {
    id: "AOBAGRECL", label: "AOBAGRECL", importLabel: "Importar AOBAGRECL",
    columns: [
      { id: "_acciones",        label: "",                       align: "left"  },
      { id: "id_objecion",      label: "ID objeción",            align: "left"  },
      { id: "distribuidor",     label: "Distribuidor",           align: "left"  },
      { id: "comercializador",  label: "Comercializador",        align: "left"  },
      { id: "nivel_tension",    label: "Nivel tensión",          align: "left"  },
      { id: "tarifa_acceso",    label: "Tarifa de acceso",       align: "left"  },
      { id: "disc_horaria",     label: "Disc. horaria",          align: "left"  },
      { id: "tipo_punto",       label: "Tipo punto",             align: "left"  },
      { id: "provincia",        label: "Provincia",              align: "left"  },
      { id: "tipo_demanda",     label: "Tipo demanda",           align: "left"  },
      { id: "periodo",          label: "Periodo",                align: "left"  },
      { id: "motivo",           label: "Motivo objeción",        align: "left"  },
      { id: "magnitud",         label: "Magnitud",               align: "left"  },
      { id: "e_publicada",      label: "E. publicada (kWh)",     align: "right" },
      { id: "e_propuesta",      label: "E. propuesta (kWh)",     align: "right" },
      { id: "comentario_emisor",label: "Comentario emisor",      align: "left"  },
      { id: "autoobjecion",     label: "Autoobjeción",           align: "left"  },
      { id: "aceptacion",       label: "Aceptada",               align: "left"  },
    ],
    camposLectura: [
      { id: "nombre_fichero",   label: "Fichero"                   },
      { id: "id_objecion",      label: "ID objeción"               },
      { id: "distribuidor",     label: "Distribuidor"              },
      { id: "comercializador",  label: "Comercializador"           },
      { id: "nivel_tension",    label: "Nivel de tensión"          },
      { id: "tarifa_acceso",    label: "Tarifa de acceso"          },
      { id: "disc_horaria",     label: "Discriminación horaria"    },
      { id: "tipo_punto",       label: "Tipo de punto"             },
      { id: "provincia",        label: "Provincia"                 },
      { id: "tipo_demanda",     label: "Tipo de demanda"           },
      { id: "periodo",          label: "Periodo"                   },
      { id: "motivo",           label: "Motivo de objeción"        },
      { id: "magnitud",         label: "Magnitud"                  },
      { id: "e_publicada",      label: "E. activa publicada (kWh)" },
      { id: "e_propuesta",      label: "E. activa propuesta (kWh)"},
      { id: "comentario_emisor",label: "Comentario del emisor"     },
      { id: "autoobjecion",     label: "Objeción a autoobjeción"   },
    ],
  },
  {
    id: "OBJEINCL", label: "OBJEINCL", importLabel: "Importar OBJEINCL",
    columns: [
      { id: "_acciones",        label: "",                          align: "left"  },
      { id: "cups",             label: "CUPS",                      align: "left"  },
      { id: "periodo",          label: "Periodo",                   align: "left"  },
      { id: "motivo",           label: "Motivo",                    align: "left"  },
      { id: "ae_publicada",     label: "AE publicada (kWh)",        align: "right" },
      { id: "ae_propuesta",     label: "AE propuesta (kWh)",        align: "right" },
      { id: "as_publicada",     label: "AS publicada (kWh)",        align: "right" },
      { id: "as_propuesta",     label: "AS propuesta (kWh)",        align: "right" },
      { id: "comentario_emisor",label: "Comentario",                align: "left"  },
      { id: "autoobjecion",     label: "Autoobjeción",              align: "left"  },
      { id: "aceptacion",       label: "Aceptada",                  align: "left"  },
    ],
    camposLectura: [
      { id: "nombre_fichero",   label: "Fichero"                   },
      { id: "cups",             label: "CUPS"                       },
      { id: "periodo",          label: "Periodo de la objeción"     },
      { id: "motivo",           label: "Motivo"                     },
      { id: "ae_publicada",     label: "AE publicada (kWh)"         },
      { id: "ae_propuesta",     label: "AE propuesta (kWh)"         },
      { id: "as_publicada",     label: "AS publicada (kWh)"         },
      { id: "as_propuesta",     label: "AS propuesta (kWh)"         },
      { id: "comentario_emisor",label: "Comentario"                 },
      { id: "autoobjecion",     label: "Objeción a autoobjeción"    },
    ],
  },
  {
    id: "AOBCUPS", label: "AOBCUPS", importLabel: "Importar AOBCUPS",
    columns: [
      { id: "_acciones",           label: "",                          align: "left"  },
      { id: "id_objecion",         label: "ID objeción",               align: "left"  },
      { id: "cups",                label: "CUPS",                      align: "left"  },
      { id: "periodo",             label: "Periodo",                   align: "left"  },
      { id: "motivo",              label: "Motivo",                    align: "left"  },
      { id: "e_publicada",         label: "E. publicada (kWh)",        align: "right" },
      { id: "e_propuesta",         label: "E. propuesta (kWh)",        align: "right" },
      { id: "comentario_emisor",   label: "Comentario emisor",         align: "left"  },
      { id: "autoobjecion",        label: "Autoobjeción (S/N)",        align: "left"  },
      { id: "aceptacion",          label: "Aceptada",                  align: "left"  },
      { id: "motivo_no_aceptacion",label: "Motivo no acept.",          align: "left"  },
      { id: "comentario_respuesta",label: "Comentario respuesta",      align: "left"  },
      { id: "magnitud",            label: "Magnitud",                  align: "left"  },
    ],
    camposLectura: [
      { id: "nombre_fichero",    label: "Fichero"                        },
      { id: "id_objecion",       label: "ID objeción"                    },
      { id: "cups",              label: "CUPS"                           },
      { id: "periodo",           label: "Periodo de cierre objetado"     },
      { id: "motivo",            label: "Motivo de objeción"             },
      { id: "e_publicada",       label: "E. activa publicada (kWh)"      },
      { id: "e_propuesta",       label: "E. activa propuesta (kWh)"      },
      { id: "comentario_emisor", label: "Comentario del emisor"          },
      { id: "autoobjecion",      label: "Objeción a autoobjeción (S/N)"  },
      { id: "magnitud",          label: "Magnitud"                       },
    ],
  },
  {
    id: "AOBCIL", label: "AOBCIL", importLabel: "Importar AOBCIL",
    columns: [
      { id: "_acciones",    label: "",                              align: "left"  },
      { id: "id_objecion",  label: "ID objeción",                  align: "left"  },
      { id: "cil",          label: "CIL",                          align: "left"  },
      { id: "periodo",      label: "Periodo",                      align: "left"  },
      { id: "motivo",       label: "Motivo",                       align: "left"  },
      { id: "eas_publicada",label: "E. act. sal. pub. (kWh)",      align: "right" },
      { id: "eas_propuesta",label: "E. act. sal. prop. (kWh)",     align: "right" },
      { id: "eq2_publicada",label: "E. react. Q2 pub. (kVArh)",   align: "right" },
      { id: "eq2_propuesta",label: "E. react. Q2 prop. (kVArh)",  align: "right" },
      { id: "eq3_publicada",label: "E. react. Q3 pub. (kVArh)",   align: "right" },
      { id: "eq3_propuesta",label: "E. react. Q3 prop. (kVArh)",  align: "right" },
      { id: "comentario_emisor",label: "Comentario emisor",        align: "left"  },
      { id: "autoobjecion", label: "Autoobjeción",                 align: "left"  },
      { id: "aceptacion",   label: "Aceptada",                     align: "left"  },
    ],
    camposLectura: [
      { id: "nombre_fichero",label: "Fichero"                        },
      { id: "id_objecion",   label: "ID objeción"                    },
      { id: "cil",           label: "CIL"                            },
      { id: "periodo",       label: "Periodo de cierre objetado"     },
      { id: "motivo",        label: "Motivo de objeción"             },
      { id: "eas_publicada", label: "E. activa saliente pub. (kWh)"  },
      { id: "eas_propuesta", label: "E. activa saliente prop. (kWh)" },
      { id: "eq2_publicada", label: "E. reactiva Q2 pub. (kVArh)"   },
      { id: "eq2_propuesta", label: "E. reactiva Q2 prop. (kVArh)"  },
      { id: "eq3_publicada", label: "E. reactiva Q3 pub. (kVArh)"   },
      { id: "eq3_propuesta", label: "E. reactiva Q3 prop. (kVArh)"  },
      { id: "comentario_emisor",label: "Comentario del emisor"       },
      { id: "autoobjecion",  label: "Objeción a autoobjeción"        },
    ],
  },
];