"""add bald columns to medidas_general

Revision ID: 5ac3aec4a5cf
Revises: 145f8ccc0249
Create Date: 2026-02-12 22:14:41.446150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac3aec4a5cf'
down_revision: Union[str, Sequence[str], None] = '145f8ccc0249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medidas_general', sa.Column('energia_publicada_m2_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_autoconsumo_m2_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_pf_m2_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_frontera_dd_m2_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_generada_m2_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_publicada_m7_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_autoconsumo_m7_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_pf_m7_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_frontera_dd_m7_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_generada_m7_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_publicada_m11_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_autoconsumo_m11_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_pf_m11_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_frontera_dd_m11_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_generada_m11_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_publicada_art15_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_autoconsumo_art15_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_pf_art15_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_frontera_dd_art15_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_generada_art15_kwh', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medidas_general', 'energia_generada_art15_kwh')
    op.drop_column('medidas_general', 'energia_frontera_dd_art15_kwh')
    op.drop_column('medidas_general', 'energia_pf_art15_kwh')
    op.drop_column('medidas_general', 'energia_autoconsumo_art15_kwh')
    op.drop_column('medidas_general', 'energia_publicada_art15_kwh')
    op.drop_column('medidas_general', 'energia_generada_m11_kwh')
    op.drop_column('medidas_general', 'energia_frontera_dd_m11_kwh')
    op.drop_column('medidas_general', 'energia_pf_m11_kwh')
    op.drop_column('medidas_general', 'energia_autoconsumo_m11_kwh')
    op.drop_column('medidas_general', 'energia_publicada_m11_kwh')
    op.drop_column('medidas_general', 'energia_generada_m7_kwh')
    op.drop_column('medidas_general', 'energia_frontera_dd_m7_kwh')
    op.drop_column('medidas_general', 'energia_pf_m7_kwh')
    op.drop_column('medidas_general', 'energia_autoconsumo_m7_kwh')
    op.drop_column('medidas_general', 'energia_publicada_m7_kwh')
    op.drop_column('medidas_general', 'energia_generada_m2_kwh')
    op.drop_column('medidas_general', 'energia_frontera_dd_m2_kwh')
    op.drop_column('medidas_general', 'energia_pf_m2_kwh')
    op.drop_column('medidas_general', 'energia_autoconsumo_m2_kwh')
    op.drop_column('medidas_general', 'energia_publicada_m2_kwh')
    # ### end Alembic commands ###
