"""add ui_theme_overrides to users

Revision ID: 650f314a7029
Revises: 80af0e2c4235
Create Date: 2026-02-27 11:26:36.804739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650f314a7029'
down_revision: Union[str, Sequence[str], None] = '80af0e2c4235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ui_theme_overrides', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ui_theme_overrides')
    # ### end Alembic commands ###
