"""create ingestion and medidas tables

Revision ID: 87f3e5c0b197
Revises: fd4bce0415f1
Create Date: 2026-03-05 01:34:02.199830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f3e5c0b197'
down_revision: Union[str, Sequence[str], None] = 'fd4bce0415f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_ok', sa.Integer(), nullable=True),
    sa.Column('rows_error', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_files_empresa_id'), 'ingestion_files', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_ingestion_files_id'), 'ingestion_files', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_files_tenant_id'), 'ingestion_files', ['tenant_id'], unique=False)
    op.create_table('medidas_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('punto_id', sa.String(length=50), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('energia_bruta_facturada', sa.Float(), nullable=True),
    sa.Column('energia_autoconsumo_kwh', sa.Float(), nullable=True),
    sa.Column('energia_generada_kwh', sa.Float(), nullable=True),
    sa.Column('energia_frontera_dd_kwh', sa.Float(), nullable=True),
    sa.Column('energia_pf_kwh', sa.Float(), nullable=True),
    sa.Column('energia_pf_final_kwh', sa.Float(), nullable=True),
    sa.Column('energia_neta_facturada_kwh', sa.Float(), nullable=True),
    sa.Column('perdidas_e_facturada_kwh', sa.Float(), nullable=True),
    sa.Column('perdidas_e_facturada_pct', sa.Float(), nullable=True),
    sa.Column('energia_publicada_m2_kwh', sa.Float(), nullable=True),
    sa.Column('energia_autoconsumo_m2_kwh', sa.Float(), nullable=True),
    sa.Column('energia_pf_m2_kwh', sa.Float(), nullable=True),
    sa.Column('energia_frontera_dd_m2_kwh', sa.Float(), nullable=True),
    sa.Column('energia_generada_m2_kwh', sa.Float(), nullable=True),
    sa.Column('energia_neta_facturada_m2_kwh', sa.Float(), nullable=True),
    sa.Column('perdidas_e_facturada_m2_kwh', sa.Float(), nullable=True),
    sa.Column('perdidas_e_facturada_m2_pct', sa.Float(), nullable=True),
    sa.Column('energia_publicada_m7_kwh', sa.Float(), nullable=True),
    sa.Column('energia_autoconsumo_m7_kwh', sa.Float(), nullable=True),
    sa.Column('energia_pf_m7_kwh', sa.Float(), nullable=True),
    sa.Column('energia_frontera_dd_m7_kwh', sa.Float(), nullable=True),
    sa.Column('energia_generada_m7_kwh', sa.Float(), nullable=True),
    sa.Column('energia_neta_facturada_m7_kwh', sa.Float(), nullable=True),
    sa.Column('perdidas_e_facturada_m7_kwh', sa.Float(), nullable=True),
    sa.Column('perdidas_e_facturada_m7_pct', sa.Float(), nullable=True),
    sa.Column('energia_publicada_m11_kwh', sa.Float(), nullable=True),
    sa.Column('energia_autoconsumo_m11_kwh', sa.Float(), nullable=True),
    sa.Column('energia_pf_m11_kwh', sa.Float(), nullable=True),
    sa.Column('energia_frontera_dd_m11_kwh', sa.Float(), nullable=True),
    sa.Column('energia_generada_m11_kwh', sa.Float(), nullable=True),
    sa.Column('energia_neta_facturada_m11_kwh', sa.Float(), nullable=True),
    sa.Column('perdidas_e_facturada_m11_kwh', sa.Float(), nullable=True),
    sa.Column('perdidas_e_facturada_m11_pct', sa.Float(), nullable=True),
    sa.Column('energia_publicada_art15_kwh', sa.Float(), nullable=True),
    sa.Column('energia_autoconsumo_art15_kwh', sa.Float(), nullable=True),
    sa.Column('energia_pf_art15_kwh', sa.Float(), nullable=True),
    sa.Column('energia_frontera_dd_art15_kwh', sa.Float(), nullable=True),
    sa.Column('energia_generada_art15_kwh', sa.Float(), nullable=True),
    sa.Column('energia_neta_facturada_art15_kwh', sa.Float(), nullable=True),
    sa.Column('perdidas_e_facturada_art15_kwh', sa.Float(), nullable=True),
    sa.Column('perdidas_e_facturada_art15_pct', sa.Float(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['ingestion_files.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medidas_general_anio'), 'medidas_general', ['anio'], unique=False)
    op.create_index(op.f('ix_medidas_general_empresa_id'), 'medidas_general', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_medidas_general_file_id'), 'medidas_general', ['file_id'], unique=False)
    op.create_index(op.f('ix_medidas_general_mes'), 'medidas_general', ['mes'], unique=False)
    op.create_index(op.f('ix_medidas_general_punto_id'), 'medidas_general', ['punto_id'], unique=False)
    op.create_index(op.f('ix_medidas_general_tenant_id'), 'medidas_general', ['tenant_id'], unique=False)
    op.create_table('medidas_micro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('punto_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('energia_kwh', sa.Float(), nullable=True),
    sa.Column('potencia_kw', sa.Float(), nullable=True),
    sa.Column('calidad', sa.String(length=20), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['ingestion_files.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medidas_micro_empresa_id'), 'medidas_micro', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_medidas_micro_punto_id'), 'medidas_micro', ['punto_id'], unique=False)
    op.create_index(op.f('ix_medidas_micro_source_file_id'), 'medidas_micro', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_medidas_micro_tenant_id'), 'medidas_micro', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_medidas_micro_timestamp'), 'medidas_micro', ['timestamp'], unique=False)
    op.create_table('medidas_ps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('punto_id', sa.String(length=50), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('energia_ps_tipo_1_kwh', sa.Float(), nullable=True),
    sa.Column('energia_ps_tipo_2_kwh', sa.Float(), nullable=True),
    sa.Column('energia_ps_tipo_3_kwh', sa.Float(), nullable=True),
    sa.Column('energia_ps_tipo_4_kwh', sa.Float(), nullable=True),
    sa.Column('energia_ps_tipo_5_kwh', sa.Float(), nullable=True),
    sa.Column('energia_ps_total_kwh', sa.Float(), nullable=True),
    sa.Column('cups_tipo_1', sa.Integer(), nullable=True),
    sa.Column('cups_tipo_2', sa.Integer(), nullable=True),
    sa.Column('cups_tipo_3', sa.Integer(), nullable=True),
    sa.Column('cups_tipo_4', sa.Integer(), nullable=True),
    sa.Column('cups_tipo_5', sa.Integer(), nullable=True),
    sa.Column('cups_total', sa.Integer(), nullable=True),
    sa.Column('importe_tipo_1_eur', sa.Float(), nullable=True),
    sa.Column('importe_tipo_2_eur', sa.Float(), nullable=True),
    sa.Column('importe_tipo_3_eur', sa.Float(), nullable=True),
    sa.Column('importe_tipo_4_eur', sa.Float(), nullable=True),
    sa.Column('importe_tipo_5_eur', sa.Float(), nullable=True),
    sa.Column('importe_total_eur', sa.Float(), nullable=True),
    sa.Column('energia_tarifa_20td_kwh', sa.Float(), nullable=True),
    sa.Column('cups_tarifa_20td', sa.Integer(), nullable=True),
    sa.Column('importe_tarifa_20td_eur', sa.Float(), nullable=True),
    sa.Column('energia_tarifa_30td_kwh', sa.Float(), nullable=True),
    sa.Column('cups_tarifa_30td', sa.Integer(), nullable=True),
    sa.Column('importe_tarifa_30td_eur', sa.Float(), nullable=True),
    sa.Column('energia_tarifa_30tdve_kwh', sa.Float(), nullable=True),
    sa.Column('cups_tarifa_30tdve', sa.Integer(), nullable=True),
    sa.Column('importe_tarifa_30tdve_eur', sa.Float(), nullable=True),
    sa.Column('energia_tarifa_61td_kwh', sa.Float(), nullable=True),
    sa.Column('cups_tarifa_61td', sa.Integer(), nullable=True),
    sa.Column('importe_tarifa_61td_eur', sa.Float(), nullable=True),
    sa.Column('energia_tarifa_62td_kwh', sa.Float(), nullable=True),
    sa.Column('cups_tarifa_62td', sa.Integer(), nullable=True),
    sa.Column('importe_tarifa_62td_eur', sa.Float(), nullable=True),
    sa.Column('energia_tarifa_63td_kwh', sa.Float(), nullable=True),
    sa.Column('cups_tarifa_63td', sa.Integer(), nullable=True),
    sa.Column('importe_tarifa_63td_eur', sa.Float(), nullable=True),
    sa.Column('energia_tarifa_64td_kwh', sa.Float(), nullable=True),
    sa.Column('cups_tarifa_64td', sa.Integer(), nullable=True),
    sa.Column('importe_tarifa_64td_eur', sa.Float(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['ingestion_files.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medidas_ps_anio'), 'medidas_ps', ['anio'], unique=False)
    op.create_index(op.f('ix_medidas_ps_empresa_id'), 'medidas_ps', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_medidas_ps_file_id'), 'medidas_ps', ['file_id'], unique=False)
    op.create_index(op.f('ix_medidas_ps_mes'), 'medidas_ps', ['mes'], unique=False)
    op.create_index(op.f('ix_medidas_ps_punto_id'), 'medidas_ps', ['punto_id'], unique=False)
    op.create_index(op.f('ix_medidas_ps_tenant_id'), 'medidas_ps', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_empresas_codigo_ree'), table_name='empresas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_empresas_codigo_ree'), 'empresas', ['codigo_ree'], unique=False)
    op.drop_index(op.f('ix_medidas_ps_tenant_id'), table_name='medidas_ps')
    op.drop_index(op.f('ix_medidas_ps_punto_id'), table_name='medidas_ps')
    op.drop_index(op.f('ix_medidas_ps_mes'), table_name='medidas_ps')
    op.drop_index(op.f('ix_medidas_ps_file_id'), table_name='medidas_ps')
    op.drop_index(op.f('ix_medidas_ps_empresa_id'), table_name='medidas_ps')
    op.drop_index(op.f('ix_medidas_ps_anio'), table_name='medidas_ps')
    op.drop_table('medidas_ps')
    op.drop_index(op.f('ix_medidas_micro_timestamp'), table_name='medidas_micro')
    op.drop_index(op.f('ix_medidas_micro_tenant_id'), table_name='medidas_micro')
    op.drop_index(op.f('ix_medidas_micro_source_file_id'), table_name='medidas_micro')
    op.drop_index(op.f('ix_medidas_micro_punto_id'), table_name='medidas_micro')
    op.drop_index(op.f('ix_medidas_micro_empresa_id'), table_name='medidas_micro')
    op.drop_table('medidas_micro')
    op.drop_index(op.f('ix_medidas_general_tenant_id'), table_name='medidas_general')
    op.drop_index(op.f('ix_medidas_general_punto_id'), table_name='medidas_general')
    op.drop_index(op.f('ix_medidas_general_mes'), table_name='medidas_general')
    op.drop_index(op.f('ix_medidas_general_file_id'), table_name='medidas_general')
    op.drop_index(op.f('ix_medidas_general_empresa_id'), table_name='medidas_general')
    op.drop_index(op.f('ix_medidas_general_anio'), table_name='medidas_general')
    op.drop_table('medidas_general')
    op.drop_index(op.f('ix_ingestion_files_tenant_id'), table_name='ingestion_files')
    op.drop_index(op.f('ix_ingestion_files_id'), table_name='ingestion_files')
    op.drop_index(op.f('ix_ingestion_files_empresa_id'), table_name='ingestion_files')
    op.drop_table('ingestion_files')
    # ### end Alembic commands ###
