"""add energia neta y perdidas facturada

Revision ID: c7d37f289c51
Revises: 5ac3aec4a5cf
Create Date: 2026-02-16 12:05:52.373839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d37f289c51'
down_revision: Union[str, Sequence[str], None] = '5ac3aec4a5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medidas_general', sa.Column('energia_neta_facturada_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('perdidas_e_facturada_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('perdidas_e_facturada_pct', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_neta_facturada_m2_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('perdidas_e_facturada_m2_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('perdidas_e_facturada_m2_pct', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_neta_facturada_m7_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('perdidas_e_facturada_m7_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('perdidas_e_facturada_m7_pct', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_neta_facturada_m11_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('perdidas_e_facturada_m11_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('perdidas_e_facturada_m11_pct', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('energia_neta_facturada_art15_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('perdidas_e_facturada_art15_kwh', sa.Float(), nullable=True))
    op.add_column('medidas_general', sa.Column('perdidas_e_facturada_art15_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medidas_general', 'perdidas_e_facturada_art15_pct')
    op.drop_column('medidas_general', 'perdidas_e_facturada_art15_kwh')
    op.drop_column('medidas_general', 'energia_neta_facturada_art15_kwh')
    op.drop_column('medidas_general', 'perdidas_e_facturada_m11_pct')
    op.drop_column('medidas_general', 'perdidas_e_facturada_m11_kwh')
    op.drop_column('medidas_general', 'energia_neta_facturada_m11_kwh')
    op.drop_column('medidas_general', 'perdidas_e_facturada_m7_pct')
    op.drop_column('medidas_general', 'perdidas_e_facturada_m7_kwh')
    op.drop_column('medidas_general', 'energia_neta_facturada_m7_kwh')
    op.drop_column('medidas_general', 'perdidas_e_facturada_m2_pct')
    op.drop_column('medidas_general', 'perdidas_e_facturada_m2_kwh')
    op.drop_column('medidas_general', 'energia_neta_facturada_m2_kwh')
    op.drop_column('medidas_general', 'perdidas_e_facturada_pct')
    op.drop_column('medidas_general', 'perdidas_e_facturada_kwh')
    op.drop_column('medidas_general', 'energia_neta_facturada_kwh')
    # ### end Alembic commands ###
